// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestSolrApp.DBModels
{
    public partial class ItemTable
    {
        public long ItemId { get; set; }
        public string ItemName { get; set; }
        public long SubCategoryId { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual SubCategoryTable SubCategory { get; set; }
    }
}