// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestSolrApp.DBModels
{
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime UpdatedOnUtc { get; set; }
        public bool Deleted { get; set; }
        public string MetaKeywords { get; set; }
    }
}