// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestSolrApp.DBModels
{
    public partial class SubCategoryTable
    {
        public SubCategoryTable()
        {
            ItemTable = new HashSet<ItemTable>();
        }

        public long SubCategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public long CategoryId { get; set; }
        public DateTime UpdatedAt { get; set; }

        public virtual CategoryTable Category { get; set; }
        public virtual ICollection<ItemTable> ItemTable { get; set; }
    }
}